### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by justinmerrell** [deeepwin/lego-cnn#3]
Is this the bug that the README is referring to?

ValueError: Tensor conversion requested dtype float32_ref for Tensor with dtype float32: <tf.Tensor 'training/SGD/SGD/conv1_1/kernel/momentum/Initializer/zeros:0' shape=(7, 7, 3, 64) dtype=float32>

**Comment by deeepwin** [comment]
It is a compatibility issue, as it happens when Colab upgrades to a new package version. See https://github.com/deeepwin/lego-cnn/issues/1
