### ISSUE TITLE
File Creation

### ISSUE THREAD

**Issue by justinmerrell** [deeepwin/lego-cnn#4]
Where is the annotation.json file coming from?

**Comment by deeepwin** [comment]
This file is generated by separate script which generated the synthetic images using Blender. It includes the image file name and ground truth box per Lego in an image.

**Comment by justinmerrell** [comment]
How about the real part images? It looks like an annotation file is always being expected.

i.e. if I take a new photo do I need to annotate it first then run it against the model for the predictions?

**Comment by deeepwin** [comment]
Yes you are correct, every image needs to be annotated. The box and class id are the targets for the NN to learn. You can take a picture an make annotations using VGG Image Annotator, see https://github.com/deeepwin/lego-cnn/issues/2

**Comment by justinmerrell** [comment]
Ah, I see now. Thank you! 

I feel like some of the info in the closed issues should be integrated into the read me.
