### ISSUE TITLE
In local machine , How to draw the Box for different LegoBrick???

### ISSUE THREAD

**Issue by SimonYU999** [deeepwin/lego-cnn#5]
Hello, 
I am new to CNN, and ML.  I am learing  them  ,and I found your project, it seems very  interesting,

 I dont want to use google drive ,so  I did what you said in "Run on Local Machine"
I finished all steps, and I can get the *.H5 file for weights, And I can use 
"tmain([ 'evaluate', '--image=' + IMAGE_PATH, '--dataset=' + PATH_DATASET, '--logs=snapshots', '--weights=' + PATH_MODEL_WEIGHTS])"
in train_lego_locally.py,    everything is successful excpet :
I see your picture  with  a pile of lego bricks , every brick get a colored box drawn,  but I  evaluate the image ,  just get a grey picture for output , I installed the "GraphViz"  successfully, but  just I can not get a image with  Colored box  for every lego brick,

how to show the  colored box???  
or  Do I need to  add some code for showing it? if so ,where and what >?  Could you give me an example???
I am busy with your lego project for 1 week , just for thse missing  colored boxes 。   T_T
 
yours

**Comment by deeepwin** [comment]
Hi, the colored boxes are drawn by the python script. If you do not see boxes it probably does not detect any bricks. It is hard for me to say why based on the description. Most likely something wrong with the training. If you look in the code you find color splash. This is where boxes are drawn. You can also check the prediction results directly.

Martin

**Comment by SimonYU999** [comment]
Thanks for you replay I will check it !!
; )




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deeepwin/lego-cnn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月24日(星期六) 下午3:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [deeepwin/lego-cnn] In local machine , How to draw the Box for different LegoBrick??? (#5)





 
Hi, the colored boxes are drawn by the python script. If you do not see boxes it probably does not detect any bricks. It is hard for me to say why based on the description. Most likely something wrong with the training. If you look in the code you find color splash. This is where boxes are drawn. You can also check the prediction results directly.
 
Martin

**Comment by Devin521314** [comment]
Could you give me the website of Google Drive about the lego datasets?

**Comment by deeepwin** [comment]
You find the path in the notebook, train_lego_on_colab_github.ipynb.
